// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi8.Data;

#nullable disable

namespace WebApi8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215183934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi8.Models.AutorModel", b =>
                {
                    b.Property<int>("id_autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_autor"));

                    b.Property<string>("nm_autor")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("id_autor");

                    b.ToTable("autores");
                });

            modelBuilder.Entity("WebApi8.Models.LivroModel", b =>
                {
                    b.Property<int>("id_livro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_livro"));

                    b.Property<int>("id_autor")
                        .HasColumnType("int");

                    b.Property<string>("nm_titulo")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("id_livro");

                    b.HasIndex("id_autor");

                    b.ToTable("livros");
                });

            modelBuilder.Entity("WebApi8.Models.LivroModel", b =>
                {
                    b.HasOne("WebApi8.Models.AutorModel", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("id_autor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("WebApi8.Models.AutorModel", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
